language: python
python:
  - "3.9"

env:
  - PLATFORMIO_PROJECT_DIR="examples/arduino-blink"

install:
  - pip install platformio
    pio update
  - pio platform install file://.

script:
  - pio run -s -d $PLATFORMIO_PROJECT_DIR
