name: CI

on:
  push:
    branches:
      - master

env:
  UPLOAD_BUILD: true

jobs:
  PIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "arduino-blink"

        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install PIO
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install file://.

      - name: Build examples
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }} >> ${{ matrix.example }}/log.txt


      - name: Upload
        if: env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: PIO_${{ matrix.example }}
          path: examples/${{ matrix.example }}

  QIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "arduino-blink"
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install QIO
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          pio platform install file://.

      - name: Build examples
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }} >> ${{ matrix.example }}/log.txt
          # cp -f ${{ matrix.example }}/.*io/build/**/*.bin  ${{ matrix.example }}/

      - name: Upload
        if: env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: QIO_${{ matrix.example }}
          path: examples/${{ matrix.example }}/
